name: startup_namer
description: App that generates proposed names for a startup company.

publish_to: "none"
version: 1.1.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  english_words: ^3.1.5
  cupertino_icons: ^0.1.2
  http: ^0.12.2
  dio: ^3.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
